#!/bin/bash
cd utils
./kill
cd ../
# _LOCAL_DATA_DIR="_local_data" INDEXIFY_LOCAL_DIR="indexify-local" WATCH_FOLDER_DIR="watch-folder" INDEXIFY_EXTRACTORS_DIR="/Users/tucker/indexifyLocalRoot/tkr_indexify_local/indexify-extractors" COORDINATOR_ADDR="localhost:8950" INGESTION_ADDR="localhost:8900" supervisord -c ./supervisord.conf
_LOCAL_DATA_DIR="_local_data" INDEXIFY_LOCAL_DIR="indexify-local" WATCH_FOLDER_DIR="utils/watch-folder" COORDINATOR_ADDR="localhost:8950" INGESTION_ADDR="localhost:8900" supervisord -c ./supervisord.conf
